# Generated by Django 3.1.4 on 2020-12-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='location',
        ),
    ]
