# Generated by Django 3.1.4 on 2020-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtol', '0002_auto_20201227_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='inventory',
            field=models.TextField(default='Moscow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='location',
            field=models.CharField(default='Moscow', max_length=500),
            preserve_default=False,
        ),
    ]
