# Generated by Django 3.1.4 on 2020-12-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtol', '0003_auto_20201227_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_item',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
